import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className='flex gap-4'>
        <Link href="/" className='px-3 py-1 mx-3'>Logo</Link>
        <Link href="/" className='px-3 py-1 mx-3'>Home</Link>
        <Link href="/blog" className='px-3 py-1 mx-3'>Blog</Link>
      </nav>
        {children}
      </body>
    </html>
  );
}
